export const NODES_TABLE: string = "lionweb_nodes"
export const CONTAINMENTS_TABLE: string = "lionweb_containments"
export const REFERENCES_TABLE: string = "lionweb_references"
export const PROPERTIES_TABLE: string = "lionweb_properties"
export const RESERVED_IDS_TABLE: string = "lionweb_reserved_ids"

export const ORPHANS_NODES_TABLE: string = "lionweb_nodes_orphans"
export const ORPHANS_CONTAINMENTS_TABLE: string = "lionweb_containments_orphans"
export const ORPHANS_REFERENCES_TABLE: string = "lionweb_references_orphans"
export const ORPHANS_PROPERTIES_TABLE: string = "lionweb_properties_orphans"
