/**
 * Run all tests.
 */
import "./test.test.js"
import "./history.test.js"
import "./additional-api.test.js"
import "./bulk-import.test.js"
import "./inspectionTests.test.js"
import "./delta/test-logo-deltas.test.js"
import "./delta/test-logo-participation.test.js"
import "./delta/AnnotationCommand.test.js"
import "./delta/MoveAndReplaceChildFromContainmentInOtherParent.test.js"
import "./delta/MoveAndReplaceChildFromOtherContainmentInSameParent.test.js"
import "./delta/MoveChildFromContainmentInOtherParent.test.js"
import "./delta/MoveChildFromOtherContainmentInSameParent.test.js"
import "./delta/MoveAndReplaceChildInSameContainmentInSameParent.test.js"
import "./delta/MoveChildInSameContainmentInSameParent.test.js"
import "./delta/ReferenceCommands.test.js"
import "./delta/ChangeClassifier.test.js"
import "./delta/CompositeCommand.test.js"
import "./delta/ContinuedCommand.test.js"
import "./sequentialize-requests.test.js"
