# Docker compose filoe to run postgres database and lionweb-repository in one container.
services:
  server:
    depends_on: [db]
    image: "ghcr.io/lionweb-io/lionweb-repository"
    environment:
      NODE_ENV: production
      REQUESTS_VERBOSITY: true
      DB_VERBOSITY: true
      PGHOST: db
    ports:
      - 3005:3005

  db:
     image: postgres:16.1
     shm_size: 1g
     restart: always
     user: postgres
     volumes:
       - db-data:/var/lib/postgresql/data
     environment:
       POSTGRES_DB: "lionweb"
       POSTGRES_PASSWORD: "lionweb"
       POSTGRES_HOST: "postgres"
       POSTGRESS_USER: "postgres"
     expose:
       - 5432
     healthcheck:
       test: [ "CMD", "pg_isready" ]
       interval: 10s
       timeout: 5s
       retries: 5
     ports:
       - '5432:5432'
volumes:
 db-data:
  driver: local


