name: Build and test lioweb-repository
on: [push, pull_request]

jobs:
  # Label of the container job
  build-and-test:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-22.04
    # Docker Hub image that `container-job` executes in
    container: node:20.10

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:16.1
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: lionweb
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: install node v18
        uses: actions/setup-node@v1
        with:
          node-version: 18
      
      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Install dependencies
        run: npm install
        
      - name: setup
        run: npm run setup

      - name: tsc
        run: npm run build

      - name: start server and run tests (one step, else server will be down when tests start)
        run: |
          npm run -w @lionweb/repository-server dev-setup
          npm run -w @lionweb/repository-server dev-run &
          sleep 6
          npm run test
